version: '2'
services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports:
            - "80:5000"
        depends_on:
            - mongo
    mongo:
        image: mongo:3.4.0
